[package]
name = "powertray"
version = "0.1.0"
edition = "2024"

[dependencies]
tray-icon = "0.20.0"
image = "0.25.6"
tao = "0.32.8"
tokio = { version = "1", features = ["full"] }
async-std = "1.13.1"
